### PR TITLE
Token based authority

### PR DESCRIPTION
**Pull request by NicholasDanks**
Hi. I started to implement the token based authority.

### CODE REVIEW

**Comment by NicholasDanks** [comment]
I got totally lost at page 3 of the handouts. Which controllers are affected for the API?

**Comment by JherezTaylor** [comment]
`authentication_controller`, that's the only one that should be handling any auth tokens.

**Comment by JherezTaylor** [comment]
Sorry, the `base` and `campaign_controller` is the one you're looking for. That has a one:many relationship with `trackers`

**Comment by rjollet** [comment]
I think it is good to merge now

**Pull request merged**
