### PR TITLE
Updated securemodel, migrations and models

### PR DESCRIPTION
**Pull request by NicholasDanks**
Do not pull yet.

### CODE REVIEW

**Comment by rjollet** [comment]
ok let us know if you need help

**Comment by NicholasDanks** [comment]
I might do. But I want to bash at it and try find the solution the hard way first :) Thanks!

**Comment by NicholasDanks** [comment]
I believe it is completed. Please approve.

**Comment by JherezTaylor** [comment]
Needs a migration and model for accounts and incorporation of the join table. The updated ERD is here https://docs.google.com/drawings/d/1j2IUtyt1N9xj6THVRAWESggDU1-FWHW512JXEHB90Cs/edit

**Comment by JherezTaylor** [comment]
Sorry, disregard, this is for # 1

**Pull request merged**
